# Generated by Django 2.2.10 on 2021-11-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211112_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_choices', to='polls.Question', verbose_name='вопрос'),
        ),
    ]
