# Generated by Django 2.2.10 on 2021-11-21 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211119_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='дата старта'),
        ),
    ]
