# Generated by Django 2.2.10 on 2021-11-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211112_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchoices',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='вопрос'),
            preserve_default=False,
        ),
    ]
