# Generated by Django 2.2.10 on 2021-11-13 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211112_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Answer', verbose_name='ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 11, 13), verbose_name='дата старта'),
        ),
    ]
