# Generated by Django 2.2.10 on 2021-11-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_optionchoices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptions',
            name='question',
        ),
    ]
