# Generated by Django 2.2.10 on 2021-11-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_questionoptions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionchoices',
            name='question',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=250, verbose_name='текст'),
        ),
    ]
