# Generated by Django 2.2.10 on 2021-11-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211112_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_user', models.BigIntegerField(verbose_name='ID пользователя')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='опрос')),
            ],
        ),
    ]
